##############################################################################
## Estimator-influence audit (phontrast 2.1.0)
##
## Fairness check for the metric comparison: JSD is estimated with KDE, and so
## is phontrast's percent-overlap, so correlating JSD against *KDE* overlap is
## partly circular. This audit correlates each separation metric against a panel
## of overlap yardsticks that do NOT share JSD's machinery, to see whether JSD's
## advantage survives a neutral reference. It mirrors the LabPhon poster's
## overlap-estimator robustness analysis, recomputed with the corrected 2.1.0
## Monte-Carlo JSD.
##
## The neutral overlap estimators (kNN density, MVN Monte-Carlo, PCA-2D grid /
## convex hull) are defined and regenerated by the poster's
## reproduce_poster_figures.py. They are functions of the tokens ALONE and do
## not use phontrast, so they are invariant to the JSD fix; this script consumes
## their committed per-pair values and swaps in the 2.1.0 metrics.
##
## Inputs (manuscript/data/):
##   - mfcc13 metric table written by rerun_paper_metrics_phontrast210.R
##       (read from manuscript/outputs/); provides jsd_mc / jsd_legacy.
##   - audited_overlap_estimator_values.csv  (per-pair overlaps by estimator;
##       committed on labphon_2026 under
##       analysis/labphon_2026/outputs/audited_overlap_estimator_values_no_mmo_*.csv)
## Output: manuscript/outputs/estimator_influence_correspondence.csv
##############################################################################
BASE <- if (dir.exists("manuscript")) "manuscript" else "."
OUT  <- file.path(BASE, "outputs"); DATA <- file.path(BASE, "data")
dir.create(OUT, showWarnings = FALSE, recursive = TRUE)

mfcc_path <- file.path(OUT, "mfcc13_pairwise_phontrast210.csv")
au_path   <- file.path(DATA, "audited_overlap_estimator_values.csv")
if (!file.exists(mfcc_path)) stop("run rerun_paper_metrics_phontrast210.R first: missing ", mfcc_path)
if (!file.exists(au_path))   stop("missing ", au_path, " (see header: copy from labphon_2026 audit outputs)")

mc <- read.csv(mfcc_path)
au <- read.csv(au_path)
# R (locale collation) and the poster's Python (codepoint order) sort the vowel
# labels differently, so a pair can be (v1,v2) in one file and (v2,v1) in the
# other. Merge on an order-invariant unordered-pair key. Pillai and
# Bhattacharyya are symmetric, so the overlap yardsticks align regardless.
canon <- function(a, b) paste(pmin(a, b), pmax(a, b), sep = "")
au$.k <- canon(au$v1, au$v2); mc$.k <- canon(mc$v1, mc$v2)
m  <- merge(au, mc[, c(".k", "jsd_mc", "jsd_legacy")], by = ".k")
if (nrow(m) < nrow(au) * 0.99)
  stop("metric/overlap merge lost pairs (", nrow(m), "/", nrow(au), "): check vowel-label encoding")
message(sprintf("merged %d / %d pairs", nrow(m), nrow(au)))

## Overlap yardsticks, grouped by whose machinery they share.
yard <- data.frame(
  label = c("KDE density", "kNN density k=10", "kNN density k=25", "kNN density k=50",
            "MVN Monte-Carlo", "PCA-2D grid", "PCA-2D convex hull"),
  col   = c("overlap_kde", "overlap_knn_density_k10", "overlap_knn_density_k25",
            "overlap_knn_density_k50", "overlap_mvn_mc", "overlap_pca2_grid", "overlap_pca2_hull"),
  shares = c("KDE (JSD)", "neutral", "neutral", "neutral", "MVN (Pillai/Bhatt)", "neutral", "neutral"),
  stringsAsFactors = FALSE)
mets <- c(jsd_mc = "JSD (mc)", jsd_legacy = "JSD (legacy)", pillai = "Pillai", bhatt_dist = "Bhattacharyya")

## Rank correspondence: |Spearman| of the separation metric with overlap (more
## separation <-> less overlap, so the raw sign is negative; report magnitude).
## Bootstrap the vowel pairs for an approximate CI (pairs share vowels, so this
## understates uncertainty -- matches the poster's caveat).
set.seed(2026)
B <- 2000
boot_ci <- function(x, o) {
  n <- length(x); v <- numeric(B)
  for (b in seq_len(B)) { i <- sample.int(n, n, replace = TRUE)
    v[b] <- suppressWarnings(abs(cor(x[i], o[i], method = "spearman"))) }
  quantile(v, c(0.025, 0.975), na.rm = TRUE)
}
rows <- list()
for (j in seq_len(nrow(yard))) {
  o <- m[[yard$col[j]]]
  for (mc_col in names(mets)) {
    x <- m[[mc_col]]; ok <- is.finite(x) & is.finite(o)
    rho  <- suppressWarnings(abs(cor(x[ok], o[ok], method = "spearman")))
    pear <- suppressWarnings(abs(cor(x[ok], o[ok], method = "pearson")))
    ci   <- boot_ci(x[ok], o[ok])
    rows[[length(rows) + 1]] <- data.frame(
      yardstick = yard$label[j], shares_machinery = yard$shares[j],
      metric = mets[[mc_col]], n_pairs = sum(ok),
      abs_spearman = round(rho, 4), spearman_lo = round(ci[1], 4), spearman_hi = round(ci[2], 4),
      abs_pearson = round(pear, 4))
  }
}
tab <- do.call(rbind, rows)
write.csv(tab, file.path(OUT, "estimator_influence_correspondence.csv"), row.names = FALSE)

## Console summary: winner per yardstick + neutral-average verdict.
wide <- reshape(tab[tab$metric %in% c("JSD (mc)", "Pillai", "Bhattacharyya"),
                    c("yardstick", "shares_machinery", "metric", "abs_spearman")],
                idvar = c("yardstick", "shares_machinery"), timevar = "metric", direction = "wide")
names(wide) <- sub("abs_spearman.", "", names(wide), fixed = TRUE)
cat("\n|Spearman| of each metric with each overlap yardstick (mc JSD):\n")
for (i in seq_len(nrow(wide))) {
  r <- wide[i, c("JSD (mc)", "Pillai", "Bhattacharyya")]
  win <- names(r)[which.max(unlist(r))]
  cat(sprintf("  %-20s [%-18s]  JSD %.3f  Pillai %.3f  Bhatt %.3f   winner: %s\n",
      wide$yardstick[i], wide$shares_machinery[i], r[[1]], r[[2]], r[[3]], win))
}
neu <- wide[wide$shares_machinery == "neutral", c("JSD (mc)", "Pillai", "Bhattacharyya")]
cat(sprintf("\nNeutral-yardstick average:  JSD %.3f  Pillai %.3f  Bhatt %.3f  -> winner: %s\n",
    mean(neu[["JSD (mc)"]]), mean(neu[["Pillai"]]), mean(neu[["Bhattacharyya"]]),
    c("JSD (mc)","Pillai","Bhattacharyya")[which.max(colMeans(neu))]))
message("wrote estimator_influence_correspondence.csv")
